name: mariomalpica2
favicon: null
layout_spectrum: 0.35937856254167855
typography_spectrum: 0.007825824897736311
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8580276344437152
  lightness: 0.5462296362966299
  saturation: 0.2966913755517453
  rhythmicContrast: 0.3244631071574986
purpose: []
